# -*- coding: utf-8 -*-
"""ExemploEstadios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jxwb85V4MOiPWquy6ToeGE3b0zsUJqRs
"""

import numpy as np
import pandas as pd
import json
import folium

!python -m pip install pymongo
from pymongo import MongoClient

dataset = "https://raw.githubusercontent.com/ProfAndersonVanin/FATEC_Banco_de_Dados_NoSQL/main/material%20de%20apoio/base%20de%20dados/Coordenadas%20csv.csv "

estadios_df = pd.read_csv(dataset)

estadios_df.head(5)

dicionario = estadios_df.to_dict('records')

dicionario

cliente = MongoClient("mongodb+srv://thaismferreira42:3RzAcSqP8gCEB7YE@clusterestadios.kraihd5.mongodb.net/?retryWrites=true&w=majority")

db = cliente.get_database('futebol')

db.estadios.insert_many(dicionario)

estadios =db.estadios

estadios

list(estadios.find())

center_lat = -14.24007
center_lon = -53.18050

consulta = list(estadios.find())

df_convertido = pd.DataFrame(consulta)

df_convertido.iloc[0]

locationmap = folium.Map(location=[ center_lat, center_lon], zoom_start=5, width=800, height=600)

qtde = len(df_convertido)

qtde

for i in range(qtde):
	lng = float(df_convertido.iloc[i]['longitude'])
	lat = float(df_convertido.iloc[i]['latitude'])
	description = 'Estádio: ' + str(df_convertido.iloc[i]['nome'])+ '<br> Capacidade: ' + str(df_convertido.iloc[i]['capacidade'])
	folium.Marker( [ lat , lng ],
                popup = description,
              	icon=folium.Icon(color='red')).add_to(locationmap)

locationmap